---
title: A Bayesian Pick-the-Winner design in a randomized phase II clinical trial
author: "Chen et.al"
output:
  word_document: default
header-includes: \usepackage{bbm}
---
========================================================

```{r library, echo=FALSE,comment="",warning=FALSE,message=FALSE}

library(knitr)
library(rmarkdown)
options(scipen=3)
```


```{r set-options, echo=FALSE, cache=FALSE}
options(width=60)
opts_chunk$set(comment = "", warning = FALSE, message = FALSE, echo = TRUE, tidy = FALSE, size="small",fig.height=5)

```


```{r, echo=FALSE}
tmp99<-get.result()

```


#Hypothesis for Power Analysis
```{r, echo=FALSE, results='asis'}
cat('Comparison of ',round(tmp99$p20.tmp*100),'% versus ',round(tmp99$p10.tmp*100),'% Response Rate') 
```


#Sample Size Calculation
```{r, echo=FALSE, results='asis'}
cat(tmp99$a1)
```

#Operating Characteristics 
```{r, echo=FALSE, results='asis'}
cat(tmp99$a2)
```

##Power Analysis
```{r, echo=FALSE, results='asis'}
cat(tmp99$power)
```

##Type I error
```{r, echo=FALSE, results='asis'}
cat(tmp99$typeI)
```

#Summary
```{r, echo=FALSE, results='asis'}
cat(tmp99$a3)
```


#Tables of Power Anlaysis
```{r, echo=FALSE, results='asis'}

    tmp98 <- get.result()
    
    tmp2<-as.vector(tmp98$ans[,1])
    name1<-tmp2[tmp2!='']
    tmp3<-tmp98$tmp
    
    for(i in 1:length(tmp3))
    {
      tmp40<-tmp3[[i]]
      tmp4<-data.frame(tmp40[1:3,])
      tmp41<-as.vector(tmp40[4,])
      name2<- if(i!=4) paste(name1[i],' (',tmp41[2],')',sep='') else paste(name1[i],' (',tmp41[3],')',sep='')
      
      cat('\n-----------------------------------------------\n')
      cat('\n\n',name2,'\n')
      print(kable(tmp4))
      cat('\n',tmp41[1],'\n')
      if(i!=4) cat('\n',tmp41[2],'\n') else cat('\n',tmp41[3],'\n')
    }
    


```
 